name: "Update docker image and push to registry"

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  schedule:
    # At minute 0 past every 12th hour
    - cron: '0 */12 * * *'

jobs:
  build:
    name: "Update docker image"
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Configure"
        id: config
        run: |
          registry=ghcr.io
          ref="${{ github.ref }}"
          if [ "$ref" = "refs/heads/main" ]; then
            label=latest
          elif [ "${ref#refs/tags/}" != "$ref" ]; then
            label="${ref#refs/tags/}"
          else
            label=test
            registry=localhost:5000
          fi
          tags="${registry}/larseggert/i-d-toolchain:${label}"
          echo "::set-output name=registry::$registry"
          echo "::set-output name=label::$label"
          echo "::set-output name=tags::$tags"

      - name: "Setup docker buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Build image"
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.config.outputs.tags }}

      - name: "Run tests"
        run: |
          chmod -R a+rwX $GITHUB_WORKSPACE
          docker run -v $GITHUB_WORKSPACE:/id --cap-add=SYS_ADMIN ${{ steps.config.outputs.tags }} kdrfc -h -3 -i draft-i-d-toolchain-test-00.md
          docker run -v $GITHUB_WORKSPACE:/id --cap-add=SYS_ADMIN ${{ steps.config.outputs.tags }} mmark -html draft-i-d-toolchain-test-00.md

      - name: "Log into registry"
        if: ${{ steps.config.outputs.label != 'test' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: "Push image"
        if: ${{ steps.config.outputs.label != 'test' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.config.outputs.tags }}
